language: shell

addons:
    ssh_known_hosts: dirkheinke.de

before_install:
  - openssl aes-256-cbc -K $encrypted_496074b8526a_key -iv $encrypted_496074b8526a_iv -in travis/travis_uploader_key.enc -out /tmp/travis_uploader_key -d

script:
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/travis_uploader_key
  - ssh-add /tmp/travis_uploader_key
  - sftp uploader@dirkheinke.de:content/dirkheinke.de <<< $'put -R *'

branches:
  only:
  - master